/// Initializes the localization system.
///
/// This macro must be invoked **once** at the module level. It generates:
/// * `enum Locale` — the list of supported languages, which provides:
///   * `const COUNT: usize` — number of languages
///   * Conversions between `Locale` and `usize`:
///     * `unsafe fn from_usize_unchecked(usize) -> Locale`
///     * `impl From<Locale> for usize`
///     * `impl TryFrom<usize> for Locale`
/// * `type Expression` — a type for localized expressions
///
/// If you want to use the built-in locale storage, you can use
/// [`init_locale_with_storage!`](crate::init_locale_with_storage!).
///
/// # Examples
///
/// ```rust
/// init_locale!(EN, RU);
/// ```
#[macro_export]
macro_rules! init_locale {
    ($($variant: ident),+ $(,)?) => {
        #[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[repr(usize)]
        pub enum Locale {
            #[default]
            $($variant),+
        }

        impl Locale {
            pub const COUNT: usize = [$(stringify!($variant)),+].len();

            #[inline]
            pub unsafe fn from_usize_unchecked(value: usize) -> Self {
                core::mem::transmute(value)
            }
        }

        impl From<Locale> for usize {
            #[inline]
            fn from(locale: Locale) -> Self {
                locale as usize
            }
        }

        impl TryFrom<usize> for Locale {
            type Error = &'static str;

            fn try_from(value: usize) -> Result<Self, Self::Error> {
                if value < Locale::COUNT {
                    Ok(unsafe { Locale::from_usize_unchecked(value) })
                } else {
                    Err("Invalid value for Locale")
                }
            }
        }

        pub type Expression = [&'static str; Locale::COUNT];
    };
}

/// Initializes the localization system and the mechanism for storing the current locale.
///
/// This macro must be invoked **once** at the module level. It generates:
/// * All items generated by [`init_locale!`](crate::init_locale!)
/// * `get_locale()` and `set_locale()` — functions for managing the global current locale state
///
/// If you don't need the built-in locale storage, you can use
/// [`init_locale!`](crate::init_locale!).
///
/// # Examples
///
/// ```rust
/// init_locale_with_storage!(EN, RU);
/// ```
#[macro_export]
macro_rules! init_locale_with_storage {
    ($($variant: ident),+ $(,)?) => {
        localize_it::init_locale!($($variant),+);

        mod storage {
            use super::Locale;
            use core::sync::atomic::{AtomicUsize, Ordering};

            static CURRENT_LOCALE: AtomicUsize = AtomicUsize::new(0);

            #[inline]
            pub fn get_locale() -> Locale {
                unsafe { Locale::from_usize_unchecked(CURRENT_LOCALE.load(Ordering::Relaxed)) }
            }

            #[inline]
            pub fn set_locale(locale: Locale) {
                CURRENT_LOCALE.store(usize::from(locale), Ordering::Relaxed)
            }
        }

        pub use storage::{get_locale, set_locale};
    }
}
