/// Initializes the localization system and the mechanism for storing the current locale.
///
/// This macro must be invoked **once** at the module level. It generates:
/// * All items generated by [`init_locale!`](crate::init_locale!)
/// * Getters and setters for the current locale state in storage:
///   * As `Locale`:
///     * `fn get_locale() -> Locale`
///     * `fn set_locale(Locale)`
///   * As `usize`:
///     * `fn get_locale_as_usize() -> usize`
///     * `fn set_locale_from_usize(usize)`
///   * As `&str`:
///     * `fn get_locale_as_str() -> &'static str`
///     * `fn set_locale_from_str(&str)`
///     * `fn set_locale_from_caseless_str(&str)` — with ASCII case-insensitive matching
///
/// If you don't need the built-in locale storage, you can use
/// [`init_locale!`](crate::init_locale!).
///
/// # Examples
///
/// Default initialization (labels are identical to locale identifiers):
///
/// ```rust
/// init_locale_with_storage!(EN, RU);
/// ```
///
/// If you need human-readable labels (e.g., for a language selector UI):
///
/// ```rust
/// init_locale_with_storage!(EN => "English", RU => "Русский");
/// ```
#[macro_export]
macro_rules! init_locale_with_storage {
    ($($variant: ident),+ $(,)?) => {
        localize_it::init_locale_with_storage!($($variant => stringify!($variant)),+);
    };

    ($($variant: ident => $label: expr),+ $(,)?) => {
        localize_it::init_locale!($($variant => $label),+);

        mod storage {
            use super::Locale;
            use core::sync::atomic::{AtomicUsize, Ordering};

            static CURRENT_LOCALE: AtomicUsize = AtomicUsize::new(Locale::DEFAULT.to_usize());

            #[inline]
            pub fn get_locale() -> Locale {
                Locale::from_usize_or_default(CURRENT_LOCALE.load(Ordering::Relaxed))
            }

            #[inline]
            pub fn set_locale(locale: Locale) {
                CURRENT_LOCALE.store(locale.to_usize(), Ordering::Relaxed)
            }

            #[inline]
            pub fn get_locale_as_usize() -> usize {
                get_locale().to_usize()
            }

            #[inline]
            pub fn set_locale_from_usize(value: usize) {
                set_locale(Locale::from_usize_or_default(value))
            }

            #[inline]
            pub fn get_locale_as_str() -> &'static str {
                get_locale().to_str()
            }

            #[inline]
            pub fn set_locale_from_str(str: &str) {
                set_locale(Locale::from_str_or_default(str))
            }

            #[inline]
            pub fn set_locale_from_caseless_str(str: &str) {
                set_locale(Locale::from_caseless_str_or_default(str))
            }
        }

        pub use storage::*;
    }
}
