/// Initializes the localization system and the mechanism for storing the current locale.
///
/// This macro must be invoked **once** at the module level. It generates:
/// * All items generated by [`init_locale!`](crate::init_locale!)
/// * `pub fn get_locale() -> Locale` — a function to get the current locale state
/// * `pub fn set_locale(Locale)` — a function to set the current locale state
///
/// If you don't need the built-in locale storage, you can use
/// [`init_locale!`](crate::init_locale!).
///
/// # Examples
///
/// Default initialization (labels are identical to locale identifiers):
///
/// ```rust
/// init_locale_with_storage!(EN, RU);
/// ```
///
/// If you need human-readable labels (e.g., for a language selector UI):
///
/// ```rust
/// init_locale_with_storage!(EN => "English", RU => "Русский");
/// ```
#[macro_export]
macro_rules! init_locale_with_storage {
    ($($variant: ident),+ $(,)?) => {
        localize_it::init_locale_with_storage!($($variant => stringify!($variant)),+);
    };

    ($($variant: ident => $label: expr),+ $(,)?) => {
        localize_it::init_locale!($($variant => $label),+);

        mod storage {
            use super::Locale;
            use core::sync::atomic::{AtomicUsize, Ordering};

            static CURRENT_LOCALE: AtomicUsize = AtomicUsize::new(Locale::DEFAULT.to_usize());

            #[inline]
            pub fn get_locale() -> Locale {
                Locale::from_usize_or_default(CURRENT_LOCALE.load(Ordering::Relaxed))
            }

            #[inline]
            pub fn set_locale(locale: Locale) {
                CURRENT_LOCALE.store(locale.to_usize(), Ordering::Relaxed)
            }
        }

        pub use storage::{get_locale, set_locale};
    }
}
